//
//  MapModels.swift
//  SearchHospital
//
//  Created by Takahiro Kato on 2018/04/12.
//  Copyright (c) 2018年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Map {
    // MARK: Use cases
    
    // MARK: 初期化
    enum Initialize {
        struct Request {
            var latitude: Double
            var longitude: Double
        }
        struct Response {
            var latitude: Double
            var longitude: Double
            var isShowUserPosition: Bool
        }
        struct ViewModel {
            var state: MapInitializeState
        }
    }

    // MARK: 検索
    enum Search {
        struct Request {
            var latitude: Double?
            var longitude: Double?
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
