//
//  MapPresenter
//  SearchHospital
//
//  Created by Takahiro Kato on 2018/04/12.
//  Copyright (c) 2018年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapPresentationLogic
{
  func presentSomething(response: Map.Something.Response)
}

class MapPresenter: MapPresentationLogic
{
  weak var viewController: MapDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Map.Something.Response)
  {
    let viewModel = Map.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
