//
//  MapPresenter.swift
//  SearchHospital
//
//  Created by Takahiro Kato on 2018/04/12.
//  Copyright (c) 2018年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MapInitializeState {
    case unInitialized(latitude: Double, longitude: Double, zoomLevel: Float)
    case initialized
}

protocol MapPresentationLogic {
    func presentInitialize(response: Map.Initialize.Response)
    func presentSearch(response: Map.Search.Response)
}

class MapPresenter: MapPresentationLogic {

    weak var viewController: MapDisplayLogic?
    
    // MARK: Initialize
    func presentInitialize(response: Map.Initialize.Response) {
        var viewModel: Map.Initialize.ViewModel!

        if response.isShowUserPosition {
            viewModel = Map.Initialize.ViewModel(state: .initialized)
        } else {
            let state = MapInitializeState.unInitialized(latitude: response.latitude,
                                                         longitude: response.longitude,
                                                         zoomLevel: 16.0)
            viewModel = Map.Initialize.ViewModel(state: state)
        }
        viewController?.displayInitialize(viewModel: viewModel)
    }
    
    // MARK: 検索
    func presentSearch(response: Map.Search.Response) {
    }
}
